### ISSUE TITLE
Pattern matching in defcall/defcast

### ISSUE THREAD

**Issue by sasa1977** [yrashk/genx#9]
Introduced in 4d4cf75c98292b6716fec84dfc04cc232f9aae52
the following code won't compile:

defmodule Test do
 import GenX.GenServer  
 use GenServer.Behaviour             

 defcall get_state, state: {_,_} = tuple, do: {:reply, tuple, tuple}
 defcast get_state, state: {_,_} = tuple, do: {:noreply, tuple}
end

**Comment by yrashk** [comment]
I just tried this:

``` elixir
Erlang R15B03 (erts-5.9.3.1) [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

Compiled lib/gen.ex
Compiled lib/application.ex
Compiled lib/gen_fsm.ex
Compiled lib/gen_event.ex
Compiled lib/ct.ex
Compiled lib/gen_server.ex
Compiled lib/supervisor.ex
Generated genx.app
Interactive Elixir (0.8.0.dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Test do
...(1)> import GenX.GenServer
...(1)> 
...(1)> use GenServer.Behaviour
...(1)> 
...(1)> defcall get_state, state: {_,_} = tuple, do: {:reply, tuple, tuple}
...(1)> defcast get_state, state: {_,_} = tuple, do: {:noreply, tuple}
...(1)> end
{:module,Test,<<70,79,82,49,0,0,11,172,66,69,65,77,65,116,111,109,0,0,0,205,0,0,0,22,11,69,108,105,120,105,114,45,84,101,115,116,8,95,95,105,110,102,111,95,95,4,100,111,99,115,...>>,[true]}
```

I am on elixir master

**Comment by sasa1977** [comment]
Sorry, should have mentioned I am running 0.7.2

**Comment by yrashk** [comment]
0.8.0 is going to be released very shortly. I would suggest either using an
older revision if you're on 0.7.2, switching to master or waiting for 0.8.0
to switch to the latest genx

**Comment by sasa1977** [comment]
Agree, thank you!
